# Generated by Django 2.2.5 on 2019-09-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('platform', models.ManyToManyField(to='devices.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Jinja2Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(default='')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Platform')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Template')),
            ],
        ),
    ]
