# Generated by Django 2.2.5 on 2019-09-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='platform',
        ),
        migrations.AddField(
            model_name='template',
            name='platform',
            field=models.ManyToManyField(to='menu.Platform'),
        ),
    ]
