# Generated by Django 2.2.5 on 2019-09-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_template_jinja2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jinja2Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(default='')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Platform')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Template')),
            ],
        ),
    ]
