# Generated by Django 2.2.5 on 2019-09-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_jinja2template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='jinja2',
        ),
    ]
